# Use Ubuntu-based dev image with some D compilers and dub installed
defaults:
  image: "gitlab.vahanus.net:5050/vahanus/public/container-ubuntu-dlang-dev:latest"
  before_script:
    - command -v image-info.sh && image-info.sh || true

variables:
  # For non-Kubernetes executors, we use tcp://docker:2375
  DOCKER_HOST: tcp://docker:2375
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  # We can pass ENV vars to the pipeline
  VA_TEST: "abc"

stages:
  - lint
  - build
  - test
  - deploy

#-- Do linting on the supplied sources --------------------------------------

lint d-language:
  tags:
    - gitlabdocker
  stage: lint
  script:
      - mkdir -p build
      - ./scripts/lint-sources.sh | tee build/linter.log || true
      - if grep error linter.log ; then echo "found linter error"; false; fi
  cache:
    key: "DUB-CACHE"
    untracked: true
    paths:
      - .dub/
  artifacts:
    paths:
      - build/linter.log

lint scripts:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - gitlabdocker
  stage: lint
  script:
    - mkdir -p build
    - ./scripts/lint-scripts.sh | tee build/linter2.log || true
      - if grep error linter.log ; then echo "found linter error"; false; fi
  artifacts:
    paths:
      - build/linter2.log


#-- Build the application ---------------------------------------------------

build app and docs:
  tags:
    - gitlabdocker
  stage: build
  script:
    - ./scripts/build.sh
  cache:
    key: "DUB-CACHE"
    untracked: true
    paths:
      - .dub/
  artifacts:
    paths:
      - libva_toolbox.a
      - docs/

#-- Test the application ----------------------------------------------------

test app:
  tags:
    - gitlabdocker
  stage: test
  script:
    - ./scripts/test.sh
  cache:
    key: "DUB-CACHE"
    untracked: true
    paths:
      - .dub/
  artifacts:
    paths:
      - libva_toolbox.json
  coverage: '/\d+\.\d+\%? covered/'  # Regex für Coverage-Wert

#-- Deploy the application --------------------------------------------------

deploy_staging:
  tags:
    - gitlabdocker
  stage: deploy
  script:
    - ./scripts/deploy.sh
  environment:
    name: staging
    url: https://packages.vahanus.net
  only:
    - main

deploy_prod:
  tags:
    - gitlabdocker
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://packages.vahanus.net
  when: manual
  only:
    - main
